
;IMPORTANT, you must save this script as UTF-8 to make it work.
#Hotstring r c * ?

; NO-BREAK SPACE ; nobreakspace
	::,  :: 

; INVERTED EXCLAMATION MARK ; exclamdown
	::,!!::¡

; CENT SIGN ; cent
	::,|c::¢

; CENT SIGN ; cent
	::,c|::¢

; CENT SIGN ; cent
	::,c/::¢

; CENT SIGN ; cent
	::,/c::¢

; POUND SIGN ; sterling
	::,L-::£

; POUND SIGN ; sterling
	::,-L::£

; CURRENCY SIGN ; currency
	::,ox::¤

; CURRENCY SIGN ; currency
	::,xo::¤

; YEN SIGN ; yen
	::,=Y::¥

; YEN SIGN ; yen
	::,Y=::¥

; BROKEN BAR ; brokenbar
	::,!^::¦

; SECTION SIGN ; section
	::,os::§

; SECTION SIGN ; section
	::,so::§

; COPYRIGHT SIGN ; copyright
	::,OC::©

; FEMININE ORDINAL INDICATOR ; ordfeminine
	::,^_a::ª

; LEFT-POINTING DOUBLE ANGLE QUOTATION MARK ; guillemotleft
	::,<<::«

; NOT SIGN ; notsign
	::,,-::¬

; NOT SIGN ; notsign
	::,-,::¬

; REGISTERED SIGN ; registered
	::,Or::®

; DEGREE SIGN ; degree
	::,oo::°

; PLUS-MINUS SIGN ; plusminus
	::,+-::±

; SUPERSCRIPT TWO ; twosuperior
	::,^2::²

; SUPERSCRIPT THREE ; threesuperior
	::,^3::³

; MICRO SIGN ; mu
	::,mu::µ

; PILCROW SIGN ; paragraph
	::,p!::¶

; PILCROW SIGN ; paragraph
	::,PP::¶

; MIDDLE DOT ; periodcentered
	::,.-::·

; CEDILLA ; cedilla
	::,, ::¸

; SUPERSCRIPT ONE ; onesuperior
	::,^1::¹

; MASCULINE ORDINAL INDICATOR ; masculine
	::,^_o::º

; RIGHT-POINTING DOUBLE ANGLE QUOTATION MARK ; guillemotright
	::,>>::»

; VULGAR FRACTION ONE QUARTER ; onequarter
	::;14::¼

; VULGAR FRACTION ONE HALF ; onehalf
	::;12::½

; VULGAR FRACTION THREE QUARTERS ; threequarters
	::;34::¾

; INVERTED QUESTION MARK ; questiondown
	::,??::¿

; LATIN CAPITAL LETTER A WITH GRAVE ; Agrave
	::,\A::À

; LATIN CAPITAL LETTER A WITH ACUTE ; Aacute
	::,´A::Á

; LATIN CAPITAL LETTER A WITH ACUTE ; Aacute
	::,'A::Á

; LATIN CAPITAL LETTER A WITH CIRCUMFLEX ; Acircumflex
	::,^A::Â

; LATIN CAPITAL LETTER A WITH TILDE ; Atilde
	::,~A::Ã

; LATIN CAPITAL LETTER A WITH DIAERESIS ; Adiaeresis
	::,"A::Ä

; LATIN CAPITAL LETTER A WITH RING ABOVE ; Aring
	::,oA::Å

; LATIN CAPITAL LETTER AE ; AE
	::,AE::Æ

; LATIN CAPITAL LETTER C WITH CEDILLA ; Ccedilla
	::,,C::Ç

; LATIN CAPITAL LETTER E WITH GRAVE ; Egrave
	::,\E::È

; LATIN CAPITAL LETTER E WITH ACUTE ; Eacute
	::,´E::É

; LATIN CAPITAL LETTER E WITH ACUTE ; Eacute
	::,'E::É

; LATIN CAPITAL LETTER E WITH DIAERESIS ; Ediaeresis
	::,"E::Ë

; LATIN CAPITAL LETTER I WITH GRAVE ; Igrave
	::,\I::Ì

; LATIN CAPITAL LETTER I WITH ACUTE ; Iacute
	::,´I::Í

; LATIN CAPITAL LETTER I WITH ACUTE ; Iacute
	::,'I::Í

; LATIN CAPITAL LETTER I WITH CIRCUMFLEX ; Icircumflex
	::,^I::Î

; LATIN CAPITAL LETTER I WITH DIAERESIS ; Idiaeresis
	::,"I::Ï

; LATIN CAPITAL LETTER ETH ; ETH
	::,DH::Ð

; LATIN CAPITAL LETTER N WITH TILDE ; Ntilde
	::,~N::Ñ

; LATIN CAPITAL LETTER O WITH GRAVE ; Ograve
	::,\O::Ò

; LATIN CAPITAL LETTER O WITH ACUTE ; Oacute
	::,´O::Ó

; LATIN CAPITAL LETTER O WITH ACUTE ; Oacute
	::,'O::Ó

; LATIN CAPITAL LETTER O WITH CIRCUMFLEX ; Ocircumflex
	::,^O::Ô

; LATIN CAPITAL LETTER O WITH TILDE ; Otilde
	::,~O::Õ

; LATIN CAPITAL LETTER O WITH DIAERESIS ; Odiaeresis
	::,"O::Ö

; MULTIPLICATION SIGN ; multiply
	::,xx::×

; LATIN CAPITAL LETTER O WITH STROKE ; Oslash
	::,/O::Ø

; LATIN CAPITAL LETTER U WITH GRAVE ; Ugrave
	::,\U::Ù

; LATIN CAPITAL LETTER U WITH ACUTE ; Uacute
	::,´U::Ú

; LATIN CAPITAL LETTER U WITH ACUTE ; Uacute
	::,'U::Ú

; LATIN CAPITAL LETTER U WITH CIRCUMFLEX ; Ucircumflex
	::,^U::Û

; LATIN CAPITAL LETTER U WITH DIAERESIS ; Udiaeresis
	::,"U::Ü

; LATIN CAPITAL LETTER Y WITH ACUTE ; Yacute
	::,´Y::Ý

; LATIN CAPITAL LETTER Y WITH ACUTE ; Yacute
	::,'Y::Ý

; LATIN CAPITAL LETTER THORN ; THORN
	::,TH::Þ

; LATIN SMALL LETTER SHARP S ; ssharp
	::,ss::ß

; LATIN SMALL LETTER A WITH GRAVE ; agrave
	::,\a::à

; LATIN SMALL LETTER A WITH ACUTE ; aacute
	::,´a::á

; LATIN SMALL LETTER A WITH ACUTE ; aacute
	::,'a::á

; LATIN SMALL LETTER A WITH CIRCUMFLEX ; acircumflex
	::,^a::â

; LATIN SMALL LETTER A WITH TILDE ; atilde
	::,~a::ã

; LATIN SMALL LETTER A WITH DIAERESIS ; adiaeresis
	::,"a::ä

; LATIN SMALL LETTER A WITH RING ABOVE ; aring
	::,oa::å

; LATIN SMALL LETTER AE ; ae
	::,ae::æ

; LATIN SMALL LETTER C WITH CEDILLA ; ccedilla
	::,,c::ç

; LATIN SMALL LETTER E WITH GRAVE ; egrave
	::,\e::è

; LATIN SMALL LETTER E WITH ACUTE ; eacute
	::,´e::é

; LATIN SMALL LETTER E WITH ACUTE ; eacute
	::,'e::é

; LATIN SMALL LETTER E WITH CIRCUMFLEX ; ecircumflex
	::,^e::ê

; LATIN SMALL LETTER E WITH DIAERESIS ; ediaeresis
	::,"e::ë

; LATIN SMALL LETTER I WITH GRAVE ; igrave
	::,\i::ì

; LATIN SMALL LETTER I WITH ACUTE ; iacute
	::,´i::í

; LATIN SMALL LETTER I WITH ACUTE ; iacute
	::,'i::í

; LATIN SMALL LETTER I WITH CIRCUMFLEX ; icircumflex
	::,^i::î

; LATIN SMALL LETTER I WITH DIAERESIS ; idiaeresis
	::,"i::ï

; LATIN SMALL LETTER ETH ; eth
	::,dh::ð

; LATIN SMALL LETTER N WITH TILDE ; ntilde
	::,~n::ñ

; LATIN SMALL LETTER O WITH GRAVE ; ograve
	::,\o::ò

; LATIN SMALL LETTER O WITH ACUTE ; oacute
	::,´o::ó

; LATIN SMALL LETTER O WITH ACUTE ; oacute
	::,'o::ó

; LATIN SMALL LETTER O WITH CIRCUMFLEX ; ocircumflex
	::,^o::ô

; LATIN SMALL LETTER O WITH TILDE ; otilde
	::,~o::õ

; LATIN SMALL LETTER O WITH DIAERESIS ; odiaeresis
	::,"o::ö

; DIVISION SIGN ; division
	::,:-::÷

; LATIN SMALL LETTER O WITH STROKE ; oslash
	::,/o::ø

; LATIN SMALL LETTER U WITH GRAVE ; ugrave
	::,\u::ù

; LATIN SMALL LETTER U WITH ACUTE ; uacute
	::,´u::ú

; LATIN SMALL LETTER U WITH ACUTE ; uacute
	::,'u::ú

; LATIN SMALL LETTER U WITH CIRCUMFLEX ; ucircumflex
	::,^u::û

; LATIN SMALL LETTER U WITH DIAERESIS ; udiaeresis
	::,"u::ü

; LATIN SMALL LETTER Y WITH ACUTE ; yacute
	::,´y::ý

; LATIN SMALL LETTER Y WITH ACUTE ; yacute
	::,'y::ý

; LATIN SMALL LETTER THORN ; thorn
	::,th::þ

; LATIN SMALL LETTER Y WITH DIAERESIS ; ydiaeresis
	::,"y::ÿ

; LATIN CAPITAL LETTER A WITH MACRON ; U0100
	::,_A::Ā

; LATIN SMALL LETTER A WITH MACRON ; U0101
	::,_a::ā

; LATIN CAPITAL LETTER A WITH BREVE ; U0102
	::,bA::Ă

; LATIN CAPITAL LETTER A WITH BREVE ; U0102,uA,uAĂ,uA,uAă,uAă,uAĂ
	::,uA::Ă

; LATIN SMALL LETTER A WITH BREVE ; U0103
	::,ba::ă

; LATIN SMALL LETTER A WITH BREVE ; U0103
	::,ua::ă

; LATIN CAPITAL LETTER A WITH OGONEK ; U0104
	::,;A::Ą

; LATIN SMALL LETTER A WITH OGONEK ; U0105
	::,;a::ą

; LATIN CAPITAL LETTER C WITH ACUTE ; U0106
	::,´C::Ć

; LATIN CAPITAL LETTER C WITH ACUTE ; U0106
	::,'C::Ć

; LATIN SMALL LETTER C WITH ACUTE ; U0107
	::,´c::ć

; LATIN SMALL LETTER C WITH ACUTE ; U0107
	::,'c::ć

; LATIN CAPITAL LETTER C WITH CIRCUMFLEX ; U0108
	::,^C::Ĉ

; LATIN SMALL LETTER C WITH CIRCUMFLEX ; U0109
	::,^c::ĉ

; LATIN CAPITAL LETTER C WITH DOT ABOVE ; U010A
	::,.C::Ċ

; LATIN SMALL LETTER C WITH DOT ABOVE ; U010B
	::,.c::ċ

; LATIN CAPITAL LETTER C WITH CARON ; U010C
	::,cC::Č

; LATIN SMALL LETTER C WITH CARON ; U010D
	::,cc::č

; LATIN CAPITAL LETTER D WITH CARON ; U010E
	::,cD::Ď

; LATIN SMALL LETTER D WITH CARON ; U010F
	::,cd::ď

; LATIN CAPITAL LETTER D WITH STROKE ; Dstroke
	::,-D::Đ

; LATIN CAPITAL LETTER D WITH STROKE ; U0110
	::,/D::Đ

; LATIN SMALL LETTER D WITH STROKE ; dstroke
	::,-d::đ

; LATIN SMALL LETTER D WITH STROKE ; U0111
	::,/d::đ

; LATIN CAPITAL LETTER E WITH MACRON ; U0112
	::,_E::Ē

; LATIN SMALL LETTER E WITH MACRON ; U0113
	::,_e::ē

; LATIN CAPITAL LETTER E WITH BREVE ; U0114
	::,bE::Ĕ

; LATIN CAPITAL LETTER E WITH BREVE ; U0114
	::,uE::Ĕ

; LATIN SMALL LETTER E WITH BREVE ; U0115
	::,be::ĕ

; LATIN SMALL LETTER E WITH BREVE ; U0115
	::,ue::ĕ

; LATIN CAPITAL LETTER E WITH DOT ABOVE ; U0116
	::,.E::Ė

; LATIN SMALL LETTER E WITH DOT ABOVE ; U0117
	::,.e::ė

; LATIN CAPITAL LETTER E WITH OGONEK ; U0118
	::,;E::Ę

; LATIN SMALL LETTER E WITH OGONEK ; U0119
	::,;e::ę

; LATIN CAPITAL LETTER E WITH CARON ; U011A
	::,cE::Ě

; LATIN SMALL LETTER E WITH CARON ; U011B
	::,ce::ě

; LATIN CAPITAL LETTER G WITH CIRCUMFLEX ; U011C
	::,^G::Ĝ

; LATIN SMALL LETTER G WITH CIRCUMFLEX ; U011D
	::,^g::ĝ

; LATIN CAPITAL LETTER G WITH BREVE ; U011E
	::,bG::Ğ

; LATIN CAPITAL LETTER G WITH BREVE ; U011E
	::,uG::Ğ

; LATIN SMALL LETTER G WITH BREVE ; U011F
	::,bg::ğ

; LATIN SMALL LETTER G WITH BREVE ; U011F
	::,ug::ğ

; LATIN CAPITAL LETTER G WITH DOT ABOVE ; U0120
	::,.G::Ġ

; LATIN SMALL LETTER G WITH DOT ABOVE ; U0121
	::,.g::ġ

; LATIN CAPITAL LETTER G WITH CEDILLA ; U0122
	::,,G::Ģ

; LATIN SMALL LETTER G WITH CEDILLA ; U0123
	::,,g::ģ

; LATIN CAPITAL LETTER H WITH CIRCUMFLEX ; U0124
	::,^H::Ĥ

; LATIN SMALL LETTER H WITH CIRCUMFLEX ; U0125
	::,^h::ĥ

; LATIN CAPITAL LETTER H WITH STROKE ; U0126
	::,/H::Ħ

; LATIN SMALL LETTER H WITH STROKE ; U0127
	::,/h::ħ

; LATIN CAPITAL LETTER I WITH TILDE ; U0128
	::,~I::Ĩ

; LATIN SMALL LETTER I WITH TILDE ; U0129
	::,~i::ĩ

; LATIN CAPITAL LETTER I WITH MACRON ; U012A
	::,_I::Ī

; LATIN SMALL LETTER I WITH MACRON ; U012B
	::,_i::ī

; LATIN CAPITAL LETTER I WITH BREVE ; U012C
	::,bI::Ĭ

; LATIN CAPITAL LETTER I WITH BREVE ; U012C
	::,uI::Ĭ

; LATIN SMALL LETTER I WITH BREVE ; U012D
	::,bi::ĭ

; LATIN SMALL LETTER I WITH BREVE ; U012D
	::,ui::ĭ

; LATIN CAPITAL LETTER I WITH OGONEK ; U012E
	::,;I::Į

; LATIN SMALL LETTER I WITH OGONEK ; U012F
	::,;i::į

; LATIN CAPITAL LETTER I WITH DOT ABOVE ; U0130
	::,.I::İ

; LATIN SMALL LETTER DOTLESS I ; U0131
	::,i.::ı

; LATIN CAPITAL LETTER J WITH CIRCUMFLEX ; U0134
	::,^J::Ĵ

; LATIN SMALL LETTER J WITH CIRCUMFLEX ; U0135
	::,^j::ĵ

; LATIN CAPITAL LETTER K WITH CEDILLA ; U0136
	::,,K::Ķ

; LATIN SMALL LETTER K WITH CEDILLA ; U0137
	::,,k::ķ

; LATIN SMALL LETTER KRA ; U0138
	::,kk::ĸ

; LATIN CAPITAL LETTER L WITH ACUTE ; U0139
	::,´L::Ĺ

; LATIN CAPITAL LETTER L WITH ACUTE ; U0139
	::,'L::Ĺ

; LATIN SMALL LETTER L WITH ACUTE ; U013A
	::,´l::ĺ

; LATIN SMALL LETTER L WITH ACUTE ; U013A
	::,'l::ĺ

; LATIN CAPITAL LETTER L WITH CEDILLA ; U013B
	::,,L::Ļ

; LATIN SMALL LETTER L WITH CEDILLA ; U013C
	::,,l::ļ

; LATIN CAPITAL LETTER L WITH CARON ; U013D
	::,cL::Ľ

; LATIN SMALL LETTER L WITH CARON ; U013E
	::,cl::ľ

; LATIN CAPITAL LETTER L WITH STROKE ; U0141
	::,/L::Ł

; LATIN SMALL LETTER L WITH STROKE ; U0142
	::,/l::ł

; LATIN CAPITAL LETTER N WITH ACUTE ; U0143
	::,´N::Ń

; LATIN CAPITAL LETTER N WITH ACUTE ; U0143
	::,'N::Ń

; LATIN SMALL LETTER N WITH ACUTE ; U0144
	::,´n::ń

; LATIN SMALL LETTER N WITH ACUTE ; U0144
	::,'n::ń

; LATIN CAPITAL LETTER N WITH CEDILLA ; U0145
	::,,N::Ņ

; LATIN SMALL LETTER N WITH CEDILLA ; U0146
	::,,n::ņ

; LATIN CAPITAL LETTER N WITH CARON ; U0147
	::,cN::Ň

; LATIN SMALL LETTER N WITH CARON ; U0148
	::,cn::ň

; LATIN CAPITAL LETTER ENG ; U014A
	::,NG::Ŋ

; LATIN SMALL LETTER ENG ; U014B
	::,ng::ŋ

; LATIN CAPITAL LETTER O WITH MACRON ; U014C
	::,_O::Ō

; LATIN SMALL LETTER O WITH MACRON ; U014D
	::,_o::ō

; LATIN CAPITAL LETTER O WITH BREVE ; U014E
	::,bO::Ŏ

; LATIN CAPITAL LETTER O WITH BREVE ; U014E
	::,uO::Ŏ

; LATIN SMALL LETTER O WITH BREVE ; U014F
	::,bo::ŏ

; LATIN SMALL LETTER O WITH BREVE ; U014F
	::,uo::ŏ

; LATIN CAPITAL LETTER O WITH DOUBLE ACUTE ; U0150
	::,=O::Ő

; LATIN SMALL LETTER O WITH DOUBLE ACUTE ; U0151
	::,=o::ő

; LATIN CAPITAL LIGATURE OE ; OE
	::,OE::Œ

; LATIN SMALL LIGATURE OE ; oe
	::,oe::œ

; LATIN CAPITAL LETTER R WITH ACUTE ; U0154
	::,´R::Ŕ

; LATIN CAPITAL LETTER R WITH ACUTE ; U0154
	::,'R::Ŕ

; LATIN SMALL LETTER R WITH ACUTE ; U0155
	::,´r::ŕ

; LATIN SMALL LETTER R WITH ACUTE ; U0155
	::,'r::ŕ

; LATIN CAPITAL LETTER R WITH CEDILLA ; U0156
	::,,R::Ŗ

; LATIN SMALL LETTER R WITH CEDILLA ; U0157
	::,,r::ŗ

; LATIN CAPITAL LETTER R WITH CARON ; U0158
	::,cR::Ř

; LATIN SMALL LETTER R WITH CARON ; U0159
	::,cr::ř

; LATIN CAPITAL LETTER S WITH ACUTE ; U015A
	::,´S::Ś

; LATIN CAPITAL LETTER S WITH ACUTE ; U015A
	::,'S::Ś

; LATIN SMALL LETTER S WITH ACUTE ; U015B
	::,´s::ś

; LATIN SMALL LETTER S WITH ACUTE ; U015B
	::,'s::ś

; LATIN CAPITAL LETTER S WITH CIRCUMFLEX ; U015C
	::,^S::Ŝ

; LATIN SMALL LETTER S WITH CIRCUMFLEX ; U015D
	::,^s::ŝ

; LATIN CAPITAL LETTER S WITH CEDILLA ; U015E
	::,,S::Ş

; LATIN SMALL LETTER S WITH CEDILLA ; U015F
	::,,s::ş

; LATIN CAPITAL LETTER S WITH CARON ; U0160
	::,cS::Š

; LATIN SMALL LETTER S WITH CARON ; U0161
	::,cs::š

; LATIN CAPITAL LETTER T WITH CEDILLA ; U0162
	::,,T::Ţ

; LATIN SMALL LETTER T WITH CEDILLA ; U0163
	::,,t::ţ

; LATIN CAPITAL LETTER T WITH CARON ; U0164
	::,cT::Ť

; LATIN SMALL LETTER T WITH CARON ; U0165
	::,ct::ť

; LATIN CAPITAL LETTER T WITH STROKE ; U0166
	::,/T::Ŧ

; LATIN SMALL LETTER T WITH STROKE ; U0167
	::,/t::ŧ

; LATIN CAPITAL LETTER U WITH TILDE ; U0168
	::,~U::Ũ

; LATIN SMALL LETTER U WITH TILDE ; U0169
	::,~u::ũ

; LATIN CAPITAL LETTER U WITH MACRON ; U016A
	::,_U::Ū

; LATIN SMALL LETTER U WITH MACRON ; U016B
	::,_u::ū

; LATIN CAPITAL LETTER U WITH BREVE ; U016C
	::,bU::Ŭ

; LATIN CAPITAL LETTER U WITH BREVE ; U016C
	::,uU::Ŭ

; LATIN SMALL LETTER U WITH BREVE ; U016D
	::,bu::ŭ

; LATIN SMALL LETTER U WITH BREVE ; U016D
	::,uu::ŭ

; LATIN CAPITAL LETTER U WITH RING ABOVE ; U016E
	::,oU::Ů

; LATIN SMALL LETTER U WITH RING ABOVE ; U016F
	::,ou::ů

; LATIN CAPITAL LETTER U WITH DOUBLE ACUTE ; U0170
	::,=U::Ű

; LATIN SMALL LETTER U WITH DOUBLE ACUTE ; U0171
	::,=u::ű

; LATIN CAPITAL LETTER U WITH OGONEK ; U0172
	::,;U::Ų

; LATIN SMALL LETTER U WITH OGONEK ; U0173
	::,;u::ų

; LATIN CAPITAL LETTER W WITH CIRCUMFLEX ; U0174
	::,^W::Ŵ

; LATIN SMALL LETTER W WITH CIRCUMFLEX ; U0175
	::,^w::ŵ

; LATIN CAPITAL LETTER Y WITH CIRCUMFLEX ; U0176
	::,^Y::Ŷ

; LATIN SMALL LETTER Y WITH CIRCUMFLEX ; U0177
	::,^y::ŷ

; LATIN CAPITAL LETTER Y WITH DIAERESIS ; U0178
	::,"Y::Ÿ

; LATIN CAPITAL LETTER Z WITH ACUTE ; U0179
	::,´Z::Ź

; LATIN CAPITAL LETTER Z WITH ACUTE ; U0179
	::,'Z::Ź

; LATIN SMALL LETTER Z WITH ACUTE ; U017A
	::,´z::ź

; LATIN SMALL LETTER Z WITH ACUTE ; U017A
	::,'z::ź

; LATIN CAPITAL LETTER Z WITH DOT ABOVE ; U017B
	::,.Z::Ż

; LATIN SMALL LETTER Z WITH DOT ABOVE ; U017C
	::,.z::ż

; LATIN CAPITAL LETTER Z WITH CARON ; U017D
	::,cZ::Ž

; LATIN SMALL LETTER Z WITH CARON ; U017E
	::,cz::ž

; LATIN SMALL LETTER LONG S ; U017f
	::,fs::ſ

; LATIN SMALL LETTER B WITH STROKE ; U0180
	::,/b::ƀ

; LATIN CAPITAL LETTER I WITH STROKE ; U0197
	::,/I::Ɨ

; LATIN CAPITAL LETTER O WITH HORN ; U01A0
	::,+O::Ơ

; LATIN SMALL LETTER O WITH HORN ; U01A1
	::,+o::ơ

; LATIN CAPITAL LETTER U WITH HORN ; U01AF
	::,+U::Ư

; LATIN SMALL LETTER U WITH HORN ; U01B0
	::,+u::ư

; LATIN CAPITAL LETTER Z WITH STROKE ; U01B5
	::,/Z::Ƶ

; LATIN SMALL LETTER Z WITH STROKE ; U01B6
	::,/z::ƶ

; LATIN CAPITAL LETTER A WITH CARON ; U01CD
	::,cA::Ǎ

; LATIN SMALL LETTER A WITH CARON ; U01CE
	::,ca::ǎ

; LATIN CAPITAL LETTER I WITH CARON ; U01CF
	::,cI::Ǐ

; LATIN SMALL LETTER I WITH CARON ; U01D0
	::,ci::ǐ

; LATIN CAPITAL LETTER O WITH CARON ; U01D1
	::,cO::Ǒ

; LATIN SMALL LETTER O WITH CARON ; U01D2
	::,co::ǒ

; LATIN CAPITAL LETTER U WITH CARON ; U01D3
	::,cU::Ǔ

; LATIN SMALL LETTER U WITH CARON ; U01D4
	::,cu::ǔ

; LATIN CAPITAL LETTER U WITH DIAERESIS AND MACRON ; U01D5
	::,_"U::Ǖ

; LATIN CAPITAL LETTER U WITH DIAERESIS AND MACRON ; U01D5
	::,_Ü::Ǖ

; LATIN SMALL LETTER U WITH DIAERESIS AND MACRON ; U01D6
	::,_"u::ǖ

; LATIN CAPITAL LETTER U WITH DIAERESIS AND ACUTE ; U01D7
	::,´"U::Ǘ

; LATIN CAPITAL LETTER U WITH DIAERESIS AND ACUTE ; U01D7
	::,'"U::Ǘ

; LATIN CAPITAL LETTER U WITH DIAERESIS AND ACUTE ; U01D7
	::,'Ü::Ǘ

; LATIN SMALL LETTER U WITH DIAERESIS AND ACUTE ; U01D8
	::,´"u::ǘ

; LATIN SMALL LETTER U WITH DIAERESIS AND ACUTE ; U01D8
	::,'"u::ǘ

; LATIN SMALL LETTER U WITH DIAERESIS AND ACUTE ; U01D8
	::,'ü::ǘ

; LATIN CAPITAL LETTER U WITH DIAERESIS AND CARON ; U01D9
	::,c"U::Ǚ

; LATIN CAPITAL LETTER U WITH DIAERESIS AND CARON ; U01D9
	::,cÜ::Ǚ

; LATIN SMALL LETTER U WITH DIAERESIS AND CARON ; U01DA
	::,c"u::ǚ

; LATIN SMALL LETTER U WITH DIAERESIS AND CARON ; U01DA
	::,cü::ǚ

; LATIN CAPITAL LETTER U WITH DIAERESIS AND GRAVE ; U01DB
	::,\"U::Ǜ

; LATIN CAPITAL LETTER U WITH DIAERESIS AND GRAVE ; U01DB
	::,\Ü::Ǜ

; LATIN SMALL LETTER U WITH DIAERESIS AND GRAVE ; U01DC
	::,\"u::ǜ

; LATIN CAPITAL LETTER A WITH DIAERESIS AND MACRON ; U01DE
	::,_Ä::Ǟ

; LATIN CAPITAL LETTER A WITH DIAERESIS AND MACRON ; U01DE
	::,_"A::Ǟ

; LATIN SMALL LETTER A WITH DIAERESIS AND MACRON ; U01DF
	::,_ä::ǟ

; LATIN SMALL LETTER A WITH DIAERESIS AND MACRON ; U01DF
	::,_"a::ǟ

; LATIN CAPITAL LETTER A WITH DOT ABOVE AND MACRON ; U01E0
	::,_.A::Ǡ

; LATIN SMALL LETTER A WITH DOT ABOVE AND MACRON ; U01E1
	::,_.a::ǡ

; LATIN CAPITAL LETTER G WITH STROKE ; U01E4
	::,/G::Ǥ

; LATIN SMALL LETTER G WITH STROKE ; U01E5
	::,/g::ǥ

; LATIN CAPITAL LETTER G WITH CARON ; U01E6
	::,cG::Ǧ

; LATIN SMALL LETTER G WITH CARON ; U01E7
	::,cg::ǧ

; LATIN CAPITAL LETTER K WITH CARON ; U01E8
	::,cK::Ǩ

; LATIN SMALL LETTER K WITH CARON ; U01E9
	::,ck::ǩ

; LATIN CAPITAL LETTER O WITH OGONEK ; U01EA
	::,;O::Ǫ

; LATIN SMALL LETTER O WITH OGONEK ; U01EB
	::,;o::ǫ

; LATIN CAPITAL LETTER O WITH OGONEK AND MACRON ; U01EC
	::,_;O::Ǭ

; LATIN SMALL LETTER O WITH OGONEK AND MACRON ; U01ED
	::,_;o::ǭ

; LATIN SMALL LETTER J WITH CARON ; U01F0
	::,cj::ǰ

; LATIN CAPITAL LETTER G WITH ACUTE ; U01F4
	::,´G::Ǵ

; LATIN CAPITAL LETTER G WITH ACUTE ; U01F4
	::,'G::Ǵ

; LATIN SMALL LETTER G WITH ACUTE ; U01F5
	::,´g::ǵ

; LATIN SMALL LETTER G WITH ACUTE ; U01F5
	::,'g::ǵ

; LATIN CAPITAL LETTER N WITH GRAVE ; U01F8
	::,\N::Ǹ

; LATIN SMALL LETTER N WITH GRAVE ; U01F9
	::,\n::ǹ

; LATIN CAPITAL LETTER A WITH RING ABOVE AND ACUTE ; U01FA
	::,'Å::Ǻ

; LATIN CAPITAL LETTER A WITH RING ABOVE AND ACUTE ; U01FA
	::,o'A::Ǻ

; LATIN SMALL LETTER A WITH RING ABOVE AND ACUTE ; U01FB
	::,'å::ǻ

; LATIN SMALL LETTER A WITH RING ABOVE AND ACUTE ; U01FB
	::,o'a::ǻ

; LATIN CAPITAL LETTER O WITH STROKE AND ACUTE ; U01FE
	::,´/O::Ǿ

; LATIN CAPITAL LETTER O WITH STROKE AND ACUTE ; U01FE
	::,'/O::Ǿ

; LATIN SMALL LETTER O WITH STROKE AND ACUTE ; U01FF
	::,´/o::ǿ

; LATIN SMALL LETTER O WITH STROKE AND ACUTE ; U01FF
	::,'/o::ǿ

; LATIN CAPITAL LETTER H WITH CARON ; U021E
	::,cH::Ȟ

; LATIN SMALL LETTER H WITH CARON ; U021F
	::,ch::ȟ

; LATIN CAPITAL LETTER A WITH DOT ABOVE ; U0226
	::,.A::Ȧ

; LATIN SMALL LETTER A WITH DOT ABOVE ; U0227
	::,.a::ȧ

; LATIN CAPITAL LETTER E WITH CEDILLA ; U0228
	::,,E::Ȩ

; LATIN SMALL LETTER E WITH CEDILLA ; U0229
	::,,e::ȩ

; LATIN CAPITAL LETTER O WITH DIAERESIS AND MACRON ; U022A
	::,_Ö::Ȫ

; LATIN CAPITAL LETTER O WITH DIAERESIS AND MACRON ; U022A
	::,_"O::Ȫ

; LATIN SMALL LETTER O WITH DIAERESIS AND MACRON ; U022B
	::,_ö::ȫ

; LATIN SMALL LETTER O WITH DIAERESIS AND MACRON ; U022B
	::,_"o::ȫ

; LATIN CAPITAL LETTER O WITH TILDE AND MACRON ; U022C
	::,_~O::Ȭ

; LATIN SMALL LETTER O WITH TILDE AND MACRON ; U022D
	::,_~o::ȭ

; LATIN CAPITAL LETTER O WITH DOT ABOVE ; U022E
	::,.O::Ȯ

; LATIN SMALL LETTER O WITH DOT ABOVE ; U022F
	::,.o::ȯ

; LATIN CAPITAL LETTER O WITH DOT ABOVE AND MACRON ; U0230
	::,_.O::Ȱ

; LATIN SMALL LETTER O WITH DOT ABOVE AND MACRON ; U0231
	::,_.o::ȱ

; LATIN CAPITAL LETTER Y WITH MACRON ; U0232
	::,_Y::Ȳ

; LATIN SMALL LETTER Y WITH MACRON ; U0233
	::,_y::ȳ

; LATIN SMALL LETTER SCHWA ; U0259
	::,ee::ə

; LATIN SMALL LETTER I WITH STROKE ; U0268
	::,/i::ɨ

; LATIN CAPITAL LETTER B WITH DOT ABOVE ; U1E02
	::,.B::Ḃ

; LATIN SMALL LETTER B WITH DOT ABOVE ; U1E03
	::,.b::ḃ

; LATIN CAPITAL LETTER B WITH DOT BELOW ; U1E04
	::,!B::Ḅ

; LATIN SMALL LETTER B WITH DOT BELOW ; U1E05
	::,!b::ḅ

; LATIN CAPITAL LETTER C WITH CEDILLA AND ACUTE ; U1E08
	::,´Ç::Ḉ

; LATIN CAPITAL LETTER D WITH DOT ABOVE ; U1E0A
	::,.D::Ḋ

; LATIN SMALL LETTER D WITH DOT ABOVE ; U1E0B
	::,.d::ḋ

; LATIN CAPITAL LETTER D WITH DOT BELOW ; U1E0C
	::,!D::Ḍ

; LATIN SMALL LETTER D WITH DOT BELOW ; U1E0D
	::,!d::ḍ

; LATIN CAPITAL LETTER D WITH CEDILLA ; U1E10
	::,,D::Ḑ

; LATIN SMALL LETTER D WITH CEDILLA ; U1E11
	::,,d::ḑ

; LATIN CAPITAL LETTER E WITH MACRON AND GRAVE ; U1E14
	::,\_E::Ḕ

; LATIN SMALL LETTER E WITH MACRON AND GRAVE ; U1E15
	::,\_e::ḕ

; LATIN CAPITAL LETTER E WITH MACRON AND ACUTE ; U1E16
	::,´_E::Ḗ

; LATIN CAPITAL LETTER E WITH MACRON AND ACUTE ; U1E16
	::,'_E::Ḗ

; LATIN SMALL LETTER E WITH MACRON AND ACUTE ; U1E17
	::,´_e::ḗ

; LATIN SMALL LETTER E WITH MACRON AND ACUTE ; U1E17
	::,'_e::ḗ

; LATIN CAPITAL LETTER E WITH CEDILLA AND BREVE ; U1E1C
	::,b,E::Ḝ

; LATIN CAPITAL LETTER E WITH CEDILLA AND BREVE ; U1E1C
	::,u,E::Ḝ

; LATIN SMALL LETTER E WITH CEDILLA AND BREVE ; U1E1D
	::,b,e::ḝ

; LATIN SMALL LETTER E WITH CEDILLA AND BREVE ; U1E1D
	::,u,e::ḝ

; LATIN CAPITAL LETTER F WITH DOT ABOVE ; U1E1E
	::,.F::Ḟ

; LATIN SMALL LETTER F WITH DOT ABOVE ; U1E1F
	::,.f::ḟ

; LATIN CAPITAL LETTER G WITH MACRON ; U1E20
	::,_G::Ḡ

; LATIN SMALL LETTER G WITH MACRON ; U1E21
	::,_g::ḡ

; LATIN CAPITAL LETTER H WITH DOT ABOVE ; U1E22
	::,.H::Ḣ

; LATIN SMALL LETTER H WITH DOT ABOVE ; U1E23
	::,.h::ḣ

; LATIN CAPITAL LETTER H WITH DOT BELOW ; U1E24
	::,!H::Ḥ

; LATIN SMALL LETTER H WITH DOT BELOW ; U1E25
	::,!h::ḥ

; LATIN CAPITAL LETTER H WITH DIAERESIS ; U1E26
	::,"H::Ḧ

; LATIN SMALL LETTER H WITH DIAERESIS ; U1E27
	::,"h::ḧ

; LATIN CAPITAL LETTER H WITH CEDILLA ; U1E28
	::,,H::Ḩ

; LATIN SMALL LETTER H WITH CEDILLA ; U1E29
	::,,h::ḩ

; LATIN CAPITAL LETTER I WITH DIAERESIS AND ACUTE ; U1E2E
	::,´"I::Ḯ

; LATIN CAPITAL LETTER I WITH DIAERESIS AND ACUTE ; U1E2E
	::,'"I::Ḯ

; LATIN SMALL LETTER I WITH DIAERESIS AND ACUTE ; U1E2F
	::,´"i::ḯ

; LATIN SMALL LETTER I WITH DIAERESIS AND ACUTE ; U1E2F
	::,'"i::ḯ

; LATIN CAPITAL LETTER K WITH ACUTE ; U1E30
	::,´K::Ḱ

; LATIN CAPITAL LETTER K WITH ACUTE ; U1E30
	::,'K::Ḱ

; LATIN SMALL LETTER K WITH ACUTE ; U1E31
	::,´k::ḱ

; LATIN SMALL LETTER K WITH ACUTE ; U1E31
	::,'k::ḱ

; LATIN CAPITAL LETTER K WITH DOT BELOW ; U1E32
	::,!K::Ḳ

; LATIN SMALL LETTER K WITH DOT BELOW ; U1E33
	::,!k::ḳ

; LATIN CAPITAL LETTER L WITH DOT BELOW ; U1E36
	::,!L::Ḷ

; LATIN SMALL LETTER L WITH DOT BELOW ; U1E37
	::,!l::ḷ

; LATIN CAPITAL LETTER L WITH DOT BELOW AND MACRON ; U1E38
	::,_!L::Ḹ

; LATIN SMALL LETTER L WITH DOT BELOW AND MACRON ; U1E39
	::,_!l::ḹ

; LATIN CAPITAL LETTER M WITH ACUTE ; U1E3E
	::,´M::Ḿ

; LATIN CAPITAL LETTER M WITH ACUTE ; U1E3E
	::,'M::Ḿ

; LATIN SMALL LETTER M WITH ACUTE ; U1E3F
	::,´m::ḿ

; LATIN SMALL LETTER M WITH ACUTE ; U1E3F
	::,'m::ḿ

; LATIN CAPITAL LETTER M WITH DOT ABOVE ; U1E40
	::,.M::Ṁ

; LATIN SMALL LETTER M WITH DOT ABOVE ; U1E41
	::,.m::ṁ

; LATIN CAPITAL LETTER M WITH DOT BELOW ; U1E42
	::,!M::Ṃ

; LATIN SMALL LETTER M WITH DOT BELOW ; U1E43
	::,!m::ṃ

; LATIN CAPITAL LETTER N WITH DOT ABOVE ; U1E44
	::,.N::Ṅ

; LATIN SMALL LETTER N WITH DOT ABOVE ; U1E45
	::,.n::ṅ

; LATIN CAPITAL LETTER N WITH DOT BELOW ; U1E46
	::,!N::Ṇ

; LATIN SMALL LETTER N WITH DOT BELOW ; U1E47
	::,!n::ṇ

; LATIN CAPITAL LETTER O WITH TILDE AND ACUTE ; U1E4C
	::,´~O::Ṍ

; LATIN CAPITAL LETTER O WITH TILDE AND ACUTE ; U1E4C
	::,'~O::Ṍ

; LATIN SMALL LETTER O WITH TILDE AND ACUTE ; U1E4D
	::,´~o::ṍ

; LATIN SMALL LETTER O WITH TILDE AND ACUTE ; U1E4D
	::,'~o::ṍ

; LATIN CAPITAL LETTER O WITH TILDE AND DIAERESIS ; U1E4E
	::,"~O::Ṏ

; LATIN SMALL LETTER O WITH TILDE AND DIAERESIS ; U1E4F
	::,"~o::ṏ

; LATIN CAPITAL LETTER O WITH MACRON AND GRAVE ; U1E50
	::,\_O::Ṑ

; LATIN SMALL LETTER O WITH MACRON AND GRAVE ; U1E51
	::,\_o::ṑ

; LATIN CAPITAL LETTER O WITH MACRON AND ACUTE ; U1E52
	::,´_O::Ṓ

; LATIN CAPITAL LETTER O WITH MACRON AND ACUTE ; U1E52
	::,'_O::Ṓ

; LATIN SMALL LETTER O WITH MACRON AND ACUTE ; U1E53
	::,´_o::ṓ

; LATIN SMALL LETTER O WITH MACRON AND ACUTE ; U1E53
	::,'_o::ṓ

; LATIN CAPITAL LETTER P WITH ACUTE ; U1E54
	::,´P::Ṕ

; LATIN CAPITAL LETTER P WITH ACUTE ; U1E54
	::,'P::Ṕ

; LATIN SMALL LETTER P WITH ACUTE ; U1E55
	::,´p::ṕ

; LATIN SMALL LETTER P WITH ACUTE ; U1E55
	::,'p::ṕ

; LATIN CAPITAL LETTER P WITH DOT ABOVE ; U1E56
	::,.P::Ṗ

; LATIN SMALL LETTER P WITH DOT ABOVE ; U1E57
	::,.p::ṗ

; LATIN CAPITAL LETTER R WITH DOT ABOVE ; U1E58
	::,.R::Ṙ

; LATIN SMALL LETTER R WITH DOT ABOVE ; U1E59
	::,.r::ṙ

; LATIN CAPITAL LETTER R WITH DOT BELOW ; U1E5A
	::,!R::Ṛ

; LATIN SMALL LETTER R WITH DOT BELOW ; U1E5B
	::,!r::ṛ

; LATIN CAPITAL LETTER R WITH DOT BELOW AND MACRON ; U1E5C
	::,_!R::Ṝ

; LATIN SMALL LETTER R WITH DOT BELOW AND MACRON ; U1E5D
	::,_!r::ṝ

; LATIN CAPITAL LETTER S WITH DOT ABOVE ; U1E60
	::,.S::Ṡ

; LATIN SMALL LETTER S WITH DOT ABOVE ; U1E61
	::,.s::ṡ

; LATIN CAPITAL LETTER S WITH DOT BELOW ; U1E62
	::,!S::Ṣ

; LATIN SMALL LETTER S WITH DOT BELOW ; U1E63
	::,!s::ṣ

; LATIN CAPITAL LETTER S WITH ACUTE AND DOT ABOVE ; U1E64
	::,.´S::Ṥ

; LATIN CAPITAL LETTER S WITH ACUTE AND DOT ABOVE ; U1E64
	::,.'S::Ṥ

; LATIN SMALL LETTER S WITH ACUTE AND DOT ABOVE ; U1E65
	::,.´s::ṥ

; LATIN SMALL LETTER S WITH ACUTE AND DOT ABOVE ; U1E65
	::,.'s::ṥ

; LATIN CAPITAL LETTER S WITH DOT BELOW AND DOT ABOVE ; U1E68
	::,.!S::Ṩ

; LATIN SMALL LETTER S WITH DOT BELOW AND DOT ABOVE ; U1E69
	::,.!s::ṩ

; LATIN CAPITAL LETTER T WITH DOT ABOVE ; U1E6A
	::,.T::Ṫ

; LATIN SMALL LETTER T WITH DOT ABOVE ; U1E6B
	::,.t::ṫ

; LATIN CAPITAL LETTER T WITH DOT BELOW ; U1E6C
	::,!T::Ṭ

; LATIN SMALL LETTER T WITH DOT BELOW ; U1E6D
	::,!t::ṭ

; LATIN CAPITAL LETTER U WITH TILDE AND ACUTE ; U1E78
	::,´~U::Ṹ

; LATIN CAPITAL LETTER U WITH TILDE AND ACUTE ; U1E78
	::,'~U::Ṹ

; LATIN SMALL LETTER U WITH TILDE AND ACUTE ; U1E79
	::,´~u::ṹ

; LATIN SMALL LETTER U WITH TILDE AND ACUTE ; U1E79
	::,'~u::ṹ

; LATIN CAPITAL LETTER U WITH MACRON AND DIAERESIS ; U1E7A
	::,"_U::Ṻ

; LATIN SMALL LETTER U WITH MACRON AND DIAERESIS ; U1E7B
	::,"_u::ṻ

; LATIN CAPITAL LETTER V WITH TILDE ; U1E7C
	::,~V::Ṽ

; LATIN SMALL LETTER V WITH TILDE ; U1E7D
	::,~v::ṽ

; LATIN CAPITAL LETTER V WITH DOT BELOW ; U1E7E
	::,!V::Ṿ

; LATIN SMALL LETTER V WITH DOT BELOW ; U1E7F
	::,!v::ṿ

; LATIN CAPITAL LETTER W WITH GRAVE ; U1E80
	::,\W::Ẁ

; LATIN SMALL LETTER W WITH GRAVE ; U1E81
	::,\w::ẁ

; LATIN CAPITAL LETTER W WITH ACUTE ; U1E82
	::,´W::Ẃ

; LATIN CAPITAL LETTER W WITH ACUTE ; U1E82
	::,'W::Ẃ

; LATIN SMALL LETTER W WITH ACUTE ; U1E83
	::,´w::ẃ

; LATIN SMALL LETTER W WITH ACUTE ; U1E83
	::,'w::ẃ

; LATIN CAPITAL LETTER W WITH DIAERESIS ; U1E84
	::,"W::Ẅ

; LATIN SMALL LETTER W WITH DIAERESIS ; U1E85
	::,"w::ẅ

; LATIN CAPITAL LETTER W WITH DOT ABOVE ; U1E86
	::,.W::Ẇ

; LATIN SMALL LETTER W WITH DOT ABOVE ; U1E87
	::,.w::ẇ

; LATIN CAPITAL LETTER W WITH DOT BELOW ; U1E88
	::,!W::Ẉ

; LATIN SMALL LETTER W WITH DOT BELOW ; U1E89
	::,!w::ẉ

; LATIN CAPITAL LETTER X WITH DOT ABOVE ; U1E8A
	::,.X::Ẋ

; LATIN SMALL LETTER X WITH DOT ABOVE ; U1E8B
	::,.x::ẋ

; LATIN CAPITAL LETTER X WITH DIAERESIS ; U1E8C
	::,"X::Ẍ

; LATIN SMALL LETTER X WITH DIAERESIS ; U1E8D
	::,"x::ẍ

; LATIN CAPITAL LETTER Y WITH DOT ABOVE ; U1E8E
	::,.Y::Ẏ

; LATIN SMALL LETTER Y WITH DOT ABOVE ; U1E8F
	::,.y::ẏ

; LATIN CAPITAL LETTER Z WITH CIRCUMFLEX ; U1E90
	::,^Z::Ẑ

; LATIN SMALL LETTER Z WITH CIRCUMFLEX ; U1E91
	::,^z::ẑ

; LATIN CAPITAL LETTER Z WITH DOT BELOW ; U1E92
	::,!Z::Ẓ

; LATIN SMALL LETTER Z WITH DOT BELOW ; U1E93
	::,!z::ẓ

; LATIN SMALL LETTER T WITH DIAERESIS ; U1E97
	::,"t::ẗ

; LATIN SMALL LETTER W WITH RING ABOVE ; U1E98
	::,ow::ẘ

; LATIN SMALL LETTER Y WITH RING ABOVE ; U1E99
	::,oy::ẙ

; LATIN CAPITAL LETTER A WITH DOT BELOW ; U1EA0
	::,!A::Ạ

; LATIN SMALL LETTER A WITH DOT BELOW ; U1EA1
	::,!a::ạ

; LATIN CAPITAL LETTER A WITH HOOK ABOVE ; U1EA2
	::,?A::Ả

; LATIN SMALL LETTER A WITH HOOK ABOVE ; U1EA3
	::,?a::ả

; LATIN CAPITAL LETTER A WITH CIRCUMFLEX AND ACUTE ; U1EA4
	::,´^A::Ấ

; LATIN CAPITAL LETTER A WITH CIRCUMFLEX AND ACUTE ; U1EA4
	::,'^A::Ấ

; LATIN SMALL LETTER A WITH CIRCUMFLEX AND ACUTE ; U1EA5
	::,´^a::ấ

; LATIN SMALL LETTER A WITH CIRCUMFLEX AND ACUTE ; U1EA5
	::,'^a::ấ

; LATIN CAPITAL LETTER A WITH CIRCUMFLEX AND GRAVE ; U1EA6
	::,\^A::Ầ

; LATIN SMALL LETTER A WITH CIRCUMFLEX AND GRAVE ; U1EA7
	::,\^a::ầ

; LATIN CAPITAL LETTER A WITH CIRCUMFLEX AND HOOK ABOVE ; U1EA8
	::,?^A::Ẩ

; LATIN SMALL LETTER A WITH CIRCUMFLEX AND HOOK ABOVE ; U1EA9
	::,?^a::ẩ

; LATIN CAPITAL LETTER A WITH CIRCUMFLEX AND TILDE ; U1EAA
	::,~^A::Ẫ

; LATIN SMALL LETTER A WITH CIRCUMFLEX AND TILDE ; U1EAB
	::,~^a::ẫ

; LATIN CAPITAL LETTER A WITH CIRCUMFLEX AND DOT BELOW ; U1EAC
	::,^!A::Ậ

; LATIN SMALL LETTER A WITH CIRCUMFLEX AND DOT BELOW ; U1EAD
	::,^!a::ậ

; LATIN CAPITAL LETTER A WITH BREVE AND ACUTE ; U1EAE
	::,´bA::Ắ

; LATIN CAPITAL LETTER A WITH BREVE AND ACUTE ; U1EAE
	::,'bA::Ắ

; LATIN SMALL LETTER A WITH BREVE AND ACUTE ; U1EAF
	::,´ba::ắ

; LATIN SMALL LETTER A WITH BREVE AND ACUTE ; U1EAF
	::,'ba::ắ

; LATIN CAPITAL LETTER A WITH BREVE AND GRAVE ; U1EB0
	::,\bA::Ằ

; LATIN SMALL LETTER A WITH BREVE AND GRAVE ; U1EB1
	::,\ba::ằ

; LATIN CAPITAL LETTER A WITH BREVE AND HOOK ABOVE ; U1EB2
	::,?bA::Ẳ

; LATIN SMALL LETTER A WITH BREVE AND HOOK ABOVE ; U1EB3
	::,?ba::ẳ

; LATIN CAPITAL LETTER A WITH BREVE AND TILDE ; U1EB4
	::,~bA::Ẵ

; LATIN SMALL LETTER A WITH BREVE AND TILDE ; U1EB5
	::,~ba::ẵ

; LATIN CAPITAL LETTER A WITH BREVE AND DOT BELOW ; U1EB6
	::,b!A::Ặ

; LATIN CAPITAL LETTER A WITH BREVE AND DOT BELOW ; U1EB6
	::,u!A::Ặ

; LATIN SMALL LETTER A WITH BREVE AND DOT BELOW ; U1EB7
	::,b!a::ặ

; LATIN SMALL LETTER A WITH BREVE AND DOT BELOW ; U1EB7
	::,u!a::ặ

; LATIN CAPITAL LETTER E WITH DOT BELOW ; U1EB8
	::,!E::Ẹ

; LATIN SMALL LETTER E WITH DOT BELOW ; U1EB9
	::,!e::ẹ

; LATIN CAPITAL LETTER E WITH HOOK ABOVE ; U1EBA
	::,?E::Ẻ

; LATIN SMALL LETTER E WITH HOOK ABOVE ; U1EBB
	::,?e::ẻ

; LATIN CAPITAL LETTER E WITH TILDE ; U1EBC
	::,~E::Ẽ

; LATIN SMALL LETTER E WITH TILDE ; U1EBD
	::,~e::ẽ

; LATIN CAPITAL LETTER E WITH CIRCUMFLEX AND ACUTE ; U1EBE
	::,´^E::Ế

; LATIN CAPITAL LETTER E WITH CIRCUMFLEX AND ACUTE ; U1EBE
	::,'^E::Ế

; LATIN SMALL LETTER E WITH CIRCUMFLEX AND ACUTE ; U1EBF
	::,´^e::ế

; LATIN SMALL LETTER E WITH CIRCUMFLEX AND ACUTE ; U1EBF
	::,'^e::ế

; LATIN CAPITAL LETTER E WITH CIRCUMFLEX AND GRAVE ; U1EC0
	::,\^E::Ề

; LATIN SMALL LETTER E WITH CIRCUMFLEX AND GRAVE ; U1EC1
	::,\^e::ề

; LATIN CAPITAL LETTER E WITH CIRCUMFLEX AND HOOK ABOVE ; U1EC2
	::,?^E::Ể

; LATIN SMALL LETTER E WITH CIRCUMFLEX AND HOOK ABOVE ; U1EC3
	::,?^e::ể

; LATIN CAPITAL LETTER E WITH CIRCUMFLEX AND TILDE ; U1EC4
	::,~^E::Ễ

; LATIN SMALL LETTER E WITH CIRCUMFLEX AND TILDE ; U1EC5
	::,~^e::ễ

; LATIN CAPITAL LETTER E WITH CIRCUMFLEX AND DOT BELOW ; U1EC6
	::,^!E::Ệ

; LATIN SMALL LETTER E WITH CIRCUMFLEX AND DOT BELOW ; U1EC7
	::,^!e::ệ

; LATIN CAPITAL LETTER I WITH HOOK ABOVE ; U1EC8
	::,?I::Ỉ

; LATIN SMALL LETTER I WITH HOOK ABOVE ; U1EC9
	::,?i::ỉ

; LATIN CAPITAL LETTER I WITH DOT BELOW ; U1ECA
	::,!I::Ị

; LATIN SMALL LETTER I WITH DOT BELOW ; U1ECB
	::,!i::ị

; LATIN CAPITAL LETTER O WITH DOT BELOW ; U1ECC
	::,!O::Ọ

; LATIN SMALL LETTER O WITH DOT BELOW ; U1ECD
	::,!o::ọ

; LATIN CAPITAL LETTER O WITH HOOK ABOVE ; U1ECE
	::,?O::Ỏ

; LATIN SMALL LETTER O WITH HOOK ABOVE ; U1ECF
	::,?o::ỏ

; LATIN CAPITAL LETTER O WITH CIRCUMFLEX AND ACUTE ; U1ED0
	::,´^O::Ố

; LATIN CAPITAL LETTER O WITH CIRCUMFLEX AND ACUTE ; U1ED0
	::,'^O::Ố

; LATIN SMALL LETTER O WITH CIRCUMFLEX AND ACUTE ; U1ED1
	::,´^o::ố

; LATIN SMALL LETTER O WITH CIRCUMFLEX AND ACUTE ; U1ED1
	::,'^o::ố

; LATIN CAPITAL LETTER O WITH CIRCUMFLEX AND GRAVE ; U1ED2
	::,\^O::Ồ

; LATIN SMALL LETTER O WITH CIRCUMFLEX AND GRAVE ; U1ED3
	::,\^o::ồ

; LATIN CAPITAL LETTER O WITH CIRCUMFLEX AND HOOK ABOVE ; U1ED4
	::,?^O::Ổ

; LATIN SMALL LETTER O WITH CIRCUMFLEX AND HOOK ABOVE ; U1ED5
	::,?^o::ổ

; LATIN CAPITAL LETTER O WITH CIRCUMFLEX AND TILDE ; U1ED6
	::,~^O::Ỗ

; LATIN SMALL LETTER O WITH CIRCUMFLEX AND TILDE ; U1ED7
	::,~^o::ỗ

; LATIN CAPITAL LETTER O WITH CIRCUMFLEX AND DOT BELOW ; U1ED8
	::,^!O::Ộ

; LATIN SMALL LETTER O WITH CIRCUMFLEX AND DOT BELOW ; U1ED9
	::,^!o::ộ

; LATIN CAPITAL LETTER O WITH HORN AND ACUTE ; U1EDA
	::,´+O::Ớ

; LATIN CAPITAL LETTER O WITH HORN AND ACUTE ; U1EDA
	::,'+O::Ớ

; LATIN SMALL LETTER O WITH HORN AND ACUTE ; U1EDB
	::,´+o::ớ

; LATIN SMALL LETTER O WITH HORN AND ACUTE ; U1EDB
	::,'+o::ớ

; LATIN CAPITAL LETTER O WITH HORN AND GRAVE ; U1EDC
	::,\+O::Ờ

; LATIN SMALL LETTER O WITH HORN AND GRAVE ; U1EDD
	::,\+o::ờ

; LATIN CAPITAL LETTER O WITH HORN AND HOOK ABOVE ; U1EDE
	::,?+O::Ở

; LATIN SMALL LETTER O WITH HORN AND HOOK ABOVE ; U1EDF
	::,?+o::ở

; LATIN CAPITAL LETTER O WITH HORN AND TILDE ; U1EE0
	::,~+O::Ỡ

; LATIN SMALL LETTER O WITH HORN AND TILDE ; U1EE1
	::,~+o::ỡ

; LATIN CAPITAL LETTER O WITH HORN AND DOT BELOW ; U1EE2
	::,!+O::Ợ

; LATIN SMALL LETTER O WITH HORN AND DOT BELOW ; U1EE3
	::,!+o::ợ

; LATIN CAPITAL LETTER U WITH DOT BELOW ; U1EE4
	::,!U::Ụ

; LATIN SMALL LETTER U WITH DOT BELOW ; U1EE5
	::,!u::ụ

; LATIN CAPITAL LETTER U WITH HOOK ABOVE ; U1EE6
	::,?U::Ủ

; LATIN SMALL LETTER U WITH HOOK ABOVE ; U1EE7
	::,?u::ủ


; LATIN CAPITAL LETTER U WITH HORN AND ACUTE ; U1EE8
	::,´+U::Ứ

; LATIN CAPITAL LETTER U WITH HORN AND ACUTE ; U1EE8
	::,'+U::Ứ

; LATIN SMALL LETTER U WITH HORN AND ACUTE ; U1EE9
	::,´+u::ứ

; LATIN SMALL LETTER U WITH HORN AND ACUTE ; U1EE9
	::,'+u::ứ

; LATIN CAPITAL LETTER U WITH HORN AND GRAVE ; U1EEA
	::,\+U::Ừ

; LATIN SMALL LETTER U WITH HORN AND GRAVE ; U1EEB
	::,\+u::ừ

; LATIN CAPITAL LETTER U WITH HORN AND HOOK ABOVE ; U1EEC
	::,?+U::Ử

; LATIN SMALL LETTER U WITH HORN AND HOOK ABOVE ; U1EED
	::,?+u::ử

; LATIN CAPITAL LETTER U WITH HORN AND TILDE ; U1EEE
	::,~+U::Ữ

; LATIN SMALL LETTER U WITH HORN AND TILDE ; U1EEF
	::,~+u::ữ

; LATIN CAPITAL LETTER U WITH HORN AND DOT BELOW ; U1EF0
	::,!+U::Ự

; LATIN SMALL LETTER U WITH HORN AND DOT BELOW ; U1EF1
	::,!+u::ự

; LATIN CAPITAL LETTER Y WITH GRAVE ; U1EF2
	::,\Y::Ỳ

; LATIN SMALL LETTER Y WITH GRAVE ; U1EF3
	::,\y::ỳ

; LATIN CAPITAL LETTER Y WITH DOT BELOW ; U1EF4
	::,!Y::Ỵ

; LATIN SMALL LETTER Y WITH DOT BELOW ; U1EF5
	::,!y::ỵ

; LATIN CAPITAL LETTER Y WITH HOOK ABOVE ; U1EF6
	::,?Y::Ỷ

; LATIN SMALL LETTER Y WITH HOOK ABOVE ; U1EF7
	::,?y::ỷ

; LATIN CAPITAL LETTER Y WITH TILDE ; U1EF8
	::,~Y::Ỹ

; LATIN SMALL LETTER Y WITH TILDE ; U1EF9
	::,~y::ỹ

; PUNCTUATION SPACE ; U2008
	::, .:: 

; EN DASH ; U2013
	::,--.::–

; EM DASH ; U2014
	::,---::—

; LEFT SINGLE QUOTATION MARK ; U2018
	::,'<::‘

; LEFT SINGLE QUOTATION MARK ; U2018
	::,<'::‘

; RIGHT SINGLE QUOTATION MARK ; U2019
	::,'>::’

; RIGHT SINGLE QUOTATION MARK ; U2019
	::,>'::’

; SINGLE LOW-9 QUOTATION MARK ; U201a
	::,',::‚

; SINGLE LOW-9 QUOTATION MARK ; U201a
	::,,'::‚

; LEFT DOUBLE QUOTATION MARK ; U201c
	::,<"::“

; LEFT DOUBLE QUOTATION MARK ; U201c
	::,"<::“

; RIGHT DOUBLE QUOTATION MARK ; U201d
	::,>"::”

; RIGHT DOUBLE QUOTATION MARK ; U201d
	::,">::”

; DOUBLE LOW-9 QUOTATION MARK ; U201e
	::,,"::„

; DOUBLE LOW-9 QUOTATION MARK ; U201e
	::,",::„

; BULLET ; enfilledcircbullet
	::,.=::•

; HORIZONTAL ELLIPSIS ; ellipsis
	::,..::…

; PER MILLE SIGN ; U2030
	::,%o::‰

; SINGLE LEFT-POINTING ANGLE QUOTATION MARK ; U2039
	::,.<::‹

; SINGLE RIGHT-POINTING ANGLE QUOTATION MARK ; U203a
	::,.>::›

; INTERROBANG ; U203D
	::,!?::‽

; INTERROBANG ; U203D
	::,?!::‽

; SUPERSCRIPT ZERO ; U2070
	::,^0::⁰

; SUPERSCRIPT LATIN SMALL LETTER I ; U2071
	::,^_i::ⁱ

; SUPERSCRIPT FOUR ; U2074
	::,^4::⁴

; SUPERSCRIPT FIVE ; U2075
	::,^5::⁵

; SUPERSCRIPT SIX ; U2076
	::,^6::⁶

; SUPERSCRIPT SEVEN ; U2077
	::,^7::⁷

; SUPERSCRIPT EIGHT ; U2078
	::,^8::⁸

; SUPERSCRIPT NINE ; U2079
	::,^9::⁹

; SUPERSCRIPT PLUS SIGN ; U207A
	::,^+::⁺

; SUPERSCRIPT EQUALS SIGN ; U207C
	::,^=::⁼

; SUPERSCRIPT LEFT PARENTHESIS ; U207D
	::,^(::⁽

; SUPERSCRIPT RIGHT PARENTHESIS ; U207E
	::,^)::⁾

; SUPERSCRIPT LATIN SMALL LETTER N ; U207F
	::,^_n::ⁿ

; SUBSCRIPT ZERO ; U2080
	::,_0::₀

; SUBSCRIPT ONE ; U2081
	::,_1::₁

; SUBSCRIPT TWO ; U2082
	::,_2::₂

; SUBSCRIPT THREE ; U2083
	::,_3::₃

; SUBSCRIPT FOUR ; U2084
	::,_4::₄

; SUBSCRIPT FIVE ; U2085
	::,_5::₅

; SUBSCRIPT SIX ; U2086
	::,_6::₆

; SUBSCRIPT SEVEN ; U2087
	::,_7::₇

; SUBSCRIPT EIGHT ; U2088
	::,_8::₈

; SUBSCRIPT NINE ; U2089
	::,_9::₉

; SUBSCRIPT PLUS SIGN ; U208A
	::,_+::₊

; SUBSCRIPT EQUALS SIGN ; U208C
	::,_=::₌

; SUBSCRIPT LEFT PARENTHESIS ; U208D
	::,_(::₍

; SUBSCRIPT RIGHT PARENTHESIS ; U208E
	::,_)::₎

; EURO-CURRENCY SIGN ; U20a0
	::,CE::₠

; COLON SIGN ; U20a1
	::,C/::₡

; COLON SIGN ; U20a1
	::,/C::₡

; CRUZEIRO SIGN ; U20a2
	::,Cr::₢

; FRENCH FRANC SIGN ; U20a3
	::,Fr::₣

; LIRA SIGN ; U20a4
	::,=L::₤

; LIRA SIGN ; U20a4
	::,L=::₤

; MILL SIGN ; U20a5
	::,m/::₥

; MILL SIGN ; U20a5
	::,/m::₥

; NAIRA SIGN ; U20a6
	::,=N::₦

; NAIRA SIGN ; U20a6
	::,N=::₦

; PESETA SIGN ; U20a7
	::,Pt::₧

; RUPEE SIGN ; U20a8
	::,Rs::₨

; WON SIGN ; U20a9
	::,=W::₩

; WON SIGN ; U20a9
	::,W=::₩

; DONG SIGN ; U20ab
	::,d-::₫

; EURO SIGN ; EuroSign
	::,c=::€

; EURO SIGN ; EuroSign
	::,E=::€

; EURO SIGN ; EuroSign
	::,=c::€

; EURO SIGN ; EuroSign
	::,=e::€

; NUMERO SIGN ; numerosign
	::,NO::№

; SERVICE MARK ; U2120
	::,sm::℠

; TRADE MARK SIGN ; U2122
	::,Tm::™

; VULGAR FRACTION ONE THIRD ; U2153
	::;13::⅓

; VULGAR FRACTION TWO THIRDS ; U2154
	::;23::⅔

; VULGAR FRACTION ONE FIFTH ; U2155
	::;15::⅕

; VULGAR FRACTION TWO FIFTHS ; U2156
	::;25::⅖

; VULGAR FRACTION THREE FIFTHS ; U2157
	::;35::⅗

; VULGAR FRACTION FOUR FIFTHS ; U2158
	::;45::⅘

; VULGAR FRACTION ONE SIXTH ; U2159
	::;16::⅙

; VULGAR FRACTION FIVE SIXTHS ; U215A
	::;56::⅚

; VULGAR FRACTION ONE EIGHTH ; U215B
	::;18::⅛

; VULGAR FRACTION THREE EIGHTHS ; U215C
	::;38::⅜

; VULGAR FRACTION FIVE EIGHTHS ; U215D
	::;58::⅝

; VULGAR FRACTION SEVEN EIGHTHS ; U215E
	::;78::⅞

; LEFTWARDS ARROW ; U2190
	::,<-::←

; RIGHTWARDS ARROW ; U2192
	::,->::→

; NOT EQUAL TO ; U2260
	::,=/::≠

; NOT EQUAL TO ; U2260
	::,/=::≠

; LESS-THAN OR EQUAL TO ; U2264
	::,<=::≤

; GREATER-THAN OR EQUAL TO ; U2265
	::,>=::≥

; CIRCLED DIGIT ONE ; U2460
	::,(1)::①

; CIRCLED DIGIT TWO ; U2461
	::,(2)::②

; CIRCLED DIGIT THREE ; U2462
	::,(3)::③

; CIRCLED DIGIT FOUR ; U2463
	::,(4)::④

; CIRCLED DIGIT FIVE ; U2464
	::,(5)::⑤

; CIRCLED DIGIT SIX ; U2465
	::,(6)::⑥

; CIRCLED DIGIT SEVEN ; U2466
	::,(7)::⑦

; CIRCLED DIGIT EIGHT ; U2467
	::,(8)::⑧

; CIRCLED DIGIT NINE ; U2468
	::,(9)::⑨

; CIRCLED NUMBER TEN ; U2469
	::,(10)::⑩

; CIRCLED NUMBER ELEVEN ; U246A
	::,(11)::⑪

; CIRCLED NUMBER TWELVE ; U246B
	::,(12)::⑫

; CIRCLED NUMBER THIRTEEN ; U246C
	::,(13)::⑬

; CIRCLED NUMBER FOURTEEN ; U246D
	::,(14)::⑭

; CIRCLED NUMBER FIFTEEN ; U246E
	::,(15)::⑮

; CIRCLED NUMBER SIXTEEN ; U246F
	::,(16)::⑯

; CIRCLED NUMBER SEVENTEEN ; U2470
	::,(17)::⑰

; CIRCLED NUMBER EIGHTEEN ; U2471
	::,(18)::⑱

; CIRCLED NUMBER NINETEEN ; U2472
	::,(19)::⑲

; CIRCLED NUMBER TWENTY ; U2473
	::,(20)::⑳

; CIRCLED LATIN CAPITAL LETTER A ; U24B6
	::,(A)::Ⓐ

; CIRCLED LATIN CAPITAL LETTER B ; U24B7
	::,(B)::Ⓑ

; CIRCLED LATIN CAPITAL LETTER C ; U24B8
	::,(C)::Ⓒ

; CIRCLED LATIN CAPITAL LETTER D ; U24B9
	::,(D)::Ⓓ

; CIRCLED LATIN CAPITAL LETTER E ; U24BA
	::,(E)::Ⓔ

; CIRCLED LATIN CAPITAL LETTER F ; U24BB
	::,(F)::Ⓕ

; CIRCLED LATIN CAPITAL LETTER G ; U24BC
	::,(G)::Ⓖ

; CIRCLED LATIN CAPITAL LETTER H ; U24BD
	::,(H)::Ⓗ

; CIRCLED LATIN CAPITAL LETTER I ; U24BE
	::,(I)::Ⓘ

; CIRCLED LATIN CAPITAL LETTER J ; U24BF
	::,(J)::Ⓙ

; CIRCLED LATIN CAPITAL LETTER K ; U24C0
	::,(K)::Ⓚ

; CIRCLED LATIN CAPITAL LETTER L ; U24C1
	::,(L)::Ⓛ

; CIRCLED LATIN CAPITAL LETTER M ; U24C2
	::,(M)::Ⓜ

; CIRCLED LATIN CAPITAL LETTER N ; U24C3
	::,(N)::Ⓝ

; CIRCLED LATIN CAPITAL LETTER O ; U24C4
	::,(O)::Ⓞ

; CIRCLED LATIN CAPITAL LETTER P ; U24C5
	::,(P)::Ⓟ

; CIRCLED LATIN CAPITAL LETTER Q ; U24C6
	::,(Q)::Ⓠ

; CIRCLED LATIN CAPITAL LETTER R ; U24C7
	::,(R)::Ⓡ

; CIRCLED LATIN CAPITAL LETTER S ; U24C8
	::,(S)::Ⓢ

; CIRCLED LATIN CAPITAL LETTER T ; U24C9
	::,(T)::Ⓣ

; CIRCLED LATIN CAPITAL LETTER U ; U24CA
	::,(U)::Ⓤ

; CIRCLED LATIN CAPITAL LETTER V ; U24CB
	::,(V)::Ⓥ

; CIRCLED LATIN CAPITAL LETTER W ; U24CC
	::,(W)::Ⓦ

; CIRCLED LATIN CAPITAL LETTER X ; U24CD
	::,(X)::Ⓧ

; CIRCLED LATIN CAPITAL LETTER Y ; U24CE
	::,(Y)::Ⓨ

; CIRCLED LATIN CAPITAL LETTER Z ; U24CF
	::,(Z)::Ⓩ

; CIRCLED LATIN SMALL LETTER A ; U24D0
	::,(a)::ⓐ

; CIRCLED LATIN SMALL LETTER B ; U24D1
	::,(b)::ⓑ

; CIRCLED LATIN SMALL LETTER C ; U24D2
	::,(c)::ⓒ

; CIRCLED LATIN SMALL LETTER D ; U24D3
	::,(d)::ⓓ

; CIRCLED LATIN SMALL LETTER E ; U24D4
	::,(e)::ⓔ

; CIRCLED LATIN SMALL LETTER F ; U24D5
	::,(f)::ⓕ

; CIRCLED LATIN SMALL LETTER G ; U24D6
	::,(g)::ⓖ

; CIRCLED LATIN SMALL LETTER H ; U24D7
	::,(h)::ⓗ

; CIRCLED LATIN SMALL LETTER I ; U24D8
	::,(i)::ⓘ

; CIRCLED LATIN SMALL LETTER J ; U24D9
	::,(j)::ⓙ

; CIRCLED LATIN SMALL LETTER K ; U24DA
	::,(k)::ⓚ

; CIRCLED LATIN SMALL LETTER L ; U24DB
	::,(l)::ⓛ

; CIRCLED LATIN SMALL LETTER M ; U24DC
	::,(m)::ⓜ

; CIRCLED LATIN SMALL LETTER N ; U24DD
	::,(n)::ⓝ

; CIRCLED LATIN SMALL LETTER O ; U24DE
	::,(o)::ⓞ

; CIRCLED LATIN SMALL LETTER P ; U24DF
	::,(p)::ⓟ

; CIRCLED LATIN SMALL LETTER Q ; U24E0
	::,(q)::ⓠ

; CIRCLED LATIN SMALL LETTER R ; U24E1
	::,(r)::ⓡ

; CIRCLED LATIN SMALL LETTER S ; U24E2
	::,(s)::ⓢ

; CIRCLED LATIN SMALL LETTER T ; U24E3
	::,(t)::ⓣ

; CIRCLED LATIN SMALL LETTER U ; U24E4
	::,(u)::ⓤ

; CIRCLED LATIN SMALL LETTER V ; U24E5
	::,(v)::ⓥ

; CIRCLED LATIN SMALL LETTER W ; U24E6
	::,(w)::ⓦ

; CIRCLED LATIN SMALL LETTER X ; U24E7
	::,(x)::ⓧ

; CIRCLED LATIN SMALL LETTER Y ; U24E8
	::,(y)::ⓨ

; CIRCLED LATIN SMALL LETTER Z ; U24E9
	::,(z)::ⓩ

; CIRCLED DIGIT ZERO ; U24EA
	::,(0)::⓪

; WHITE FROWNING FACE ; U2639
	::,:(::☹

; WHITE SMILING FACE ; U263A
	::,:)::☺

; BLACK HEART SUIT ; U2665
	::,<3::♥

; MUSIC FLAT SIGN ; U266d
	::,#b::♭

; MUSIC NATURAL SIGN ; U266e
	::,#f::♮

; MUSIC SHARP SIGN ; U266f
	::,##::♯

; REVERSED DOUBLE PRIME QUOTATION MARK ; U301d
	::,"\::〝

; DOUBLE PRIME QUOTATION MARK ; U301e
	::,"/::〞

; CIRCLED NUMBER TWENTY ONE ; U3251
	::,(21)::㉑

; CIRCLED NUMBER TWENTY TWO ; U3252
	::,(22)::㉒

; CIRCLED NUMBER TWENTY THREE ; U3253
	::,(23)::㉓

; CIRCLED NUMBER TWENTY FOUR ; U3254
	::,(24)::㉔

; CIRCLED NUMBER TWENTY FIVE ; U3255
	::,(25)::㉕

; CIRCLED NUMBER TWENTY SIX ; U3256
	::,(26)::㉖

; CIRCLED NUMBER TWENTY SEVEN ; U3257
	::,(27)::㉗

; CIRCLED NUMBER TWENTY EIGHT ; U3258
	::,(28)::㉘

; CIRCLED NUMBER TWENTY NINE ; U3259
	::,(29)::㉙

; CIRCLED NUMBER THIRTY ; U325A
	::,(30)::㉚

; CIRCLED NUMBER THIRTY ONE ; U325B
	::,(31)::㉛

; CIRCLED NUMBER THIRTY TWO ; U325C
	::,(32)::㉜

; CIRCLED NUMBER THIRTY THREE ; U325D
	::,(33)::㉝

; CIRCLED NUMBER THIRTY FOUR ; U325E
	::,(34)::㉞

; CIRCLED NUMBER THIRTY FIVE ; U325F
	::,(35)::㉟

; CIRCLED NUMBER THIRTY SIX ; U32B1
	::,(36)::㊱

; CIRCLED NUMBER THIRTY SEVEN ; U32B2
	::,(37)::㊲

; CIRCLED NUMBER THIRTY EIGHT ; U32B3
	::,(38)::㊳

; CIRCLED NUMBER THIRTY NINE ; U32B4
	::,(39)::㊴

; CIRCLED NUMBER FORTY ; U32B5
	::,(40)::㊵

; CIRCLED NUMBER FORTY ONE ; U32B6
	::,(41)::㊶

; CIRCLED NUMBER FORTY TWO ; U32B7
	::,(42)::㊷

; CIRCLED NUMBER FORTY THREE ; U32B8
	::,(43)::㊸

; CIRCLED NUMBER FORTY FOUR ; U32B9
	::,(44)::㊹

; CIRCLED NUMBER FORTY FIVE ; U32BA
	::,(45)::㊺

; CIRCLED NUMBER FORTY SIX ; U32BB
	::,(46)::㊻

; CIRCLED NUMBER FORTY SEVEN ; U32BC
	::,(47)::㊼

; CIRCLED NUMBER FORTY EIGHT ; U32BD
	::,(48)::㊽

; CIRCLED NUMBER FORTY NINE ; U32BE
	::,(49)::㊾

; CIRCLED NUMBER FIFTY ; U32BF
	::,(50)::㊿

; NUMBER SIGN ; numbersign
	::,++::#

; COMMERCIAL AT ; at
	::,AT::@

; LEFT SQUARE BRACKET ; bracketleft
	::,((::[

; REVERSE SOLIDUS ; backslash
	::,</::\

; REVERSE SOLIDUS ; backslash
	::,/<::\

; REVERSE SOLIDUS ; backslash
	::,//::\

; RIGHT SQUARE BRACKET ; bracketright
	::,))::]

; CIRCUMFLEX ACCENT ; asciicircum
	::,> ::^^

; CIRCUMFLEX ACCENT ; asciicircum
	::, >::^^

; LEFT CURLY BRACKET ; braceleft
	::,-(::{

; LEFT CURLY BRACKET ; braceleft
	::,(-::{

; VERTICAL LINE ; bar
	::,^/::|

; VERTICAL LINE ; bar
	::,lv::|

; VERTICAL LINE ; bar
	::,/^::|

; VERTICAL LINE ; bar
	::,vl::|

; RIGHT CURLY BRACKET ; braceright
	::,-)::}

; RIGHT CURLY BRACKET ; braceright
	::,)-::}

